/*
 * Copyright (c) "Graph Foundation,"
 * Graph Foundation, Inc. [https://graphfoundation.org]
 *
 * This file is part of ONgDB.
 *
 * ONgDB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * Copyright (c) 2002-2020 "Neo4j,"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.neo4j.shell.commands;

import org.junit.Test;

import org.neo4j.shell.ConnectionConfig;
import org.neo4j.shell.CypherShell;
import org.neo4j.shell.StringLinePrinter;
import org.neo4j.shell.cli.Encryption;
import org.neo4j.shell.cli.Format;
import org.neo4j.shell.prettyprint.PrettyConfig;

import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeTrue;
import static org.neo4j.shell.Versions.majorVersion;

public class CypherShellProtocolIntegrationTest
{

    @Test
    public void shouldConnectWithBoltProtocol() throws Exception
    {
        CypherShell shell = new CypherShell( new StringLinePrinter(), new PrettyConfig( Format.PLAIN, true, 1000 ) );
        shell.connect( new ConnectionConfig( "bolt://", "localhost", 7687, "ongdb", "owengee", Encryption.DEFAULT ) );
        assertTrue( shell.isConnected() );
    }

    @Test
    public void shouldConnectWithBoltSSCProtocol() throws Exception
    {
        CypherShell shell = new CypherShell( new StringLinePrinter(), new PrettyConfig( Format.PLAIN, true, 1000 ) );
        // Given ONgDB 1.x, where Bolt TLS is optional and a self-signed certificate is generated by default.
        onlyInOngdb1x();
        shell.connect( new ConnectionConfig( "bolt+ssc://", "localhost", 7687, "ongdb", "owengee", Encryption.DEFAULT ) );
        assertTrue( shell.isConnected() );
    }

    // Here should be tests for "neo4j+s" and "bolt+s", but we don't have the infrastructure for those.

    private void onlyInOngdb1x() throws Exception
    {
        // Default connection settings
        CypherShell probe = new CypherShell( new StringLinePrinter(), new PrettyConfig( Format.PLAIN, true, 1000 ) );
        probe.connect( new ConnectionConfig( "bolt://", "localhost", 7687, "ongdb", "owengee", Encryption.DEFAULT ) );
        assumeTrue( majorVersion( probe.getServerVersion() ) == 1 );
    }
}
