name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: gradle
      - name: Build with Makefile
        run: |
          make info
          make build
          make test
          make untested-zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geequel-shell
          path: out/geequel-shell.zip
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: geequel-shell/build/reports/tests/test/
